import type { User, Mentor } from '@/lib/types';

export const DUMMY_USER: User = {
  id: 'user',
  name: 'Karthika',
  coins: 50,
  skillsOffered: ['Basic Python', 'Canva Design'],
  learningInterests: ['Guitar', 'Photography'],
  sessionsLearned: 2,
  sessionsTaught: 3,
  coinsEarned: 15,
  rating: 4.9,
  image: 'user-avatar',
  streakCount: 0,
  lastSessionDate: null,
};

export const DUMMY_MENTORS: Mentor[] = [
  {
    id: 'rahul',
    name: 'Rahul',
    skills: ['Guitar', 'Music Theory'],
    learningInterests: ['Songwriting', 'Audio Production'],
    sessionsProvided: 12,
    rating: 4.8,
    coinsEarned: 50,
    image: 'mentor1',
    streakCount: 0,
    lastSessionDate: null,
  },
  {
    id: 'anjali',
    name: 'Anjali',
    skills: ['Photography', 'Editing'],
    learningInterests: ['Videography', 'Drone Piloting'],
    sessionsProvided: 6,
    rating: 4.6,
    coinsEarned: 25,
    image: 'mentor2',
    streakCount: 0,
    lastSessionDate: null,
  },
  {
    id: 'arjun',
    name: 'Arjun',
    skills: ['Web Development', 'React'],
    learningInterests: ['UI/UX Design', 'DevOps'],
    sessionsProvided: 15,
    rating: 4.9,
    coinsEarned: 70,
    image: 'mentor3',
    streakCount: 0,
    lastSessionDate: null,
  },
  {
    id: 'priya',
    name: 'Priya',
    skills: ['Cooking', 'Baking'],
    learningInterests: ['Food Photography', 'Pastry Arts'],
    sessionsProvided: 20,
    rating: 4.9,
    coinsEarned: 100,
    image: 'mentor4',
    streakCount: 0,
    lastSessionDate: null,
  },
  {
    id: 'vikram',
    name: 'Vikram',
    skills: ['Yoga', 'Meditation'],
    learningInterests: ['Nutrition', 'Ayurveda'],
    sessionsProvided: 25,
    rating: 4.7,
    coinsEarned: 125,
    image: 'mentor5',
    streakCount: 0,
    lastSessionDate: null,
  },
  {
    id: 'sameer',
    name: 'Sameer',
    skills: ['Public Speaking', 'Debate'],
    learningInterests: ['Creative Writing', 'Improv Comedy'],
    sessionsProvided: 18,
    rating: 4.8,
    coinsEarned: 90,
    image: 'mentor6',
    streakCount: 0,
    lastSessionDate: null,
  },
];
